// Source of truth: prisma/menu.raw.txt
// Base language is Azerbaijani (title). English and Russian translations
// are filled in per-item below. For dishes that have no natural translation
// (proper names, brand-specific items, ingredients that don't translate),
// we transliterate — e.g. Borş → Borsh / Борщ.
//
// Set menus (Rus seti, Nastoyka seti, Çay dəstgahı) get isSet=true and
// render as premium cards on the public menu.
//
// To push these translations into the DB without wiping admin edits, run:
//   npx tsx prisma/sync-translations.ts

export interface SeedItem {
  title: string
  titleEn?: string
  titleRu?: string
  subtitle?: string
  subtitleEn?: string
  subtitleRu?: string
  description?: string
  descriptionEn?: string
  descriptionRu?: string
  price: number
  priceLabel?: string
  isSet?: boolean
}

export interface SeedCategory {
  slug: string
  name: string
  nameEn: string
  nameRu: string
  items: SeedItem[]
}

export const menuData: SeedCategory[] = [
  {
    slug: 'sorbalar',
    name: 'Şorbalar',
    nameEn: 'Soups',
    nameRu: 'Супы',
    items: [
      { title: 'Borş', titleEn: 'Borsh', titleRu: 'Борщ', price: 10 },
      { title: 'Toyuq şorbası', titleEn: 'Chicken soup', titleRu: 'Куриный суп', price: 6 },
      { title: 'Düşbərə', titleEn: 'Dushbara', titleRu: 'Дюшбара', price: 6 },
    ],
  },
  {
    slug: 'soyuq-qelyanaltilar',
    name: 'Soyuq qəlyanaltılar',
    nameEn: 'Cold Appetizers',
    nameRu: 'Холодные закуски',
    items: [
      { title: 'Tərəvəz buketi', titleEn: 'Vegetable bouquet', titleRu: 'Овощной букет', price: 10 },
      { title: 'Turşu assortisi', titleEn: 'Pickle assortment', titleRu: 'Ассорти солений', price: 12 },
      { title: 'Zeytun assortisi', titleEn: 'Olive assortment', titleRu: 'Ассорти оливок', price: 6 },
      { title: 'Badımcan ikrası', titleEn: 'Eggplant caviar', titleRu: 'Баклажанная икра', price: 5 },
      { title: 'Leço', titleEn: 'Lecho', titleRu: 'Лечо', price: 5 },
      { title: 'Dana ciyəri paşteti', titleEn: 'Veal liver pâté', titleRu: 'Паштет из телячьей печени', price: 10 },
      { title: 'Toyuq və fındıqlı paştet', titleEn: 'Chicken & hazelnut pâté', titleRu: 'Куриный паштет с фундуком', price: 10 },
      { title: 'Ət assortisi', titleEn: 'Meat assortment', titleRu: 'Мясное ассорти', price: 22 },
      { title: 'Kolbasa assortisi', titleEn: 'Sausage assortment', titleRu: 'Колбасное ассорти', price: 20 },
      { title: 'Yerli pendir tabağı', titleEn: 'Local cheese board', titleRu: 'Тарелка местных сыров', price: 15 },
      { title: 'Avropa pendirləri tabağı', titleEn: 'European cheese board', titleRu: 'Тарелка европейских сыров', price: 18 },
    ],
  },
  {
    slug: 'salatlar',
    name: 'Salatlar',
    nameEn: 'Salads',
    nameRu: 'Салаты',
    items: [
      { title: 'Pabeda ət salatı', titleEn: 'Pabeda meat salad', titleRu: 'Мясной салат Победа', price: 20 },
      { title: 'Abşeron salatı', titleEn: 'Absheron salad', titleRu: 'Салат Абшерон', price: 7 },
      { title: 'Paytaxt salatı', titleEn: 'Capital salad', titleRu: 'Салат Столичный', price: 8 },
      { title: 'Mimoza, toyuq ilə', titleEn: 'Mimosa with chicken', titleRu: 'Мимоза с курицей', price: 8 },
      { title: 'Femi', titleEn: 'Femi', titleRu: 'Феми', price: 10 },
      {
        title: 'Fit salatı',
        titleEn: 'Fit salad',
        titleRu: 'Фит-салат',
        subtitle: 'avokado, toyuq, kinoa',
        subtitleEn: 'avocado, chicken, quinoa',
        subtitleRu: 'авокадо, курица, киноа',
        price: 14,
      },
      { title: 'Şuba, siyənək ilə', titleEn: 'Shuba with herring', titleRu: 'Селёдка под шубой', price: 9 },
      { title: 'Gürcü salatı', titleEn: 'Georgian salad', titleRu: 'Грузинский салат', price: 9 },
      { title: 'Xırt-xırt badımcan salatı', titleEn: 'Crispy eggplant salad', titleRu: 'Хрустящий салат из баклажанов', price: 11 },
      { title: 'Popkorn salatı, toyuq ilə', titleEn: 'Popcorn salad with chicken', titleRu: 'Салат Попкорн с курицей', price: 16 },
      { title: 'Popkorn salatı, krevet ilə', titleEn: 'Popcorn salad with shrimp', titleRu: 'Салат Попкорн с креветками', price: 20 },
      { title: 'Sezar, toyuq ilə', titleEn: 'Caesar with chicken', titleRu: 'Цезарь с курицей', price: 16 },
      { title: 'Sezar, krevet ilə', titleEn: 'Caesar with shrimp', titleRu: 'Цезарь с креветками', price: 20 },
      { title: 'Sezar, qızıl balıq ilə', titleEn: 'Caesar with salmon', titleRu: 'Цезарь с сёмгой', price: 20 },
    ],
  },
  {
    slug: 'tez-bazar',
    name: 'Tez-bazar',
    nameEn: 'Quick Bites',
    nameRu: 'Быстрые закуски',
    items: [
      { title: 'Pabeda Burger, fri ilə', titleEn: 'Pabeda Burger with fries', titleRu: 'Бургер Победа с картофелем фри', price: 18 },
      { title: 'Sezar Roll, fri ilə', titleEn: 'Caesar Roll with fries', titleRu: 'Цезарь Ролл с картофелем фри', price: 14 },
      { title: 'Nagetslər, fri ilə', titleEn: 'Nuggets with fries', titleRu: 'Наггетсы с картофелем фри', price: 9 },
      { title: 'Pendir çubuqları', titleEn: 'Cheese sticks', titleRu: 'Сырные палочки', price: 10 },
      {
        title: 'Toyuq qanadları',
        titleEn: 'Chicken wings',
        titleRu: 'Куриные крылышки',
        subtitle: 'BBQ / acılı',
        subtitleEn: 'BBQ / spicy',
        subtitleRu: 'BBQ / острые',
        price: 12,
      },
      { title: 'Kartof fri', titleEn: 'French fries', titleRu: 'Картофель фри', price: 5 },
    ],
  },
  {
    slug: 'isti-yemekler',
    name: 'İsti yeməklər',
    nameEn: 'Hot Dishes',
    nameRu: 'Горячие блюда',
    items: [
      { title: 'Pabeda Steak', titleEn: 'Pabeda Steak', titleRu: 'Стейк Победа', price: 45 },
      { title: 'Pabeda medalyonları', titleEn: 'Pabeda medallions', titleRu: 'Медальоны Победа', price: 32 },
      { title: 'Brisket', titleEn: 'Brisket', titleRu: 'Бризкет', price: 20 },
      { title: 'Parça ət', titleEn: 'Meat pieces', titleRu: 'Мясные кусочки', price: 20 },
      { title: 'Asobuko', titleEn: 'Osso buco', titleRu: 'Оссо-буко', price: 22 },
      { title: 'Sümüyetto', titleEn: 'Sumuyetto', titleRu: 'Сюмюетто', price: 16 },
      { title: 'Can əti qutab və pendirli', titleEn: 'Tenderloin qutab with cheese', titleRu: 'Кутаб из вырезки с сыром', price: 25 },
      { title: 'Jarko, quzu əti ilə', titleEn: 'Zharkoye with lamb', titleRu: 'Жаркое с бараниной', price: 21 },
      { title: 'Jarko, can əti ilə', titleEn: 'Zharkoye with tenderloin', titleRu: 'Жаркое с вырезкой', price: 25 },
      { title: 'Vişnəli can əti', titleEn: 'Tenderloin with cherry', titleRu: 'Вырезка с вишней', price: 25 },
      { title: 'İspanaqlı can əti', titleEn: 'Tenderloin with spinach', titleRu: 'Вырезка со шпинатом', price: 25 },
      { title: 'Zirincili dana', titleEn: 'Veal with barberry', titleRu: 'Телятина с барбарисом', price: 20 },
      { title: 'Nar qovurma', titleEn: 'Pomegranate qovurma', titleRu: 'Каурма с гранатом', price: 17 },
      { title: 'Tuşonka', titleEn: 'Tushonka', titleRu: 'Тушёнка', price: 17 },
      { title: 'Ciz-biz', titleEn: 'Jiz-biz', titleRu: 'Джиз-быз', price: 12 },
    ],
  },
  {
    slug: 'toyuq-yemekleri',
    name: 'Toyuq yeməkləri',
    nameEn: 'Chicken Dishes',
    nameRu: 'Блюда из курицы',
    items: [
      { title: 'Çolpa, limonlu', titleEn: 'Cholpa with lemon', titleRu: 'Чолпа с лимоном', price: 20 },
      { title: 'Mərakeş toyuğu', titleEn: 'Moroccan chicken', titleRu: 'Марокканская курица', price: 22 },
      { title: 'Kənd toyuğu çığırtması', titleEn: 'Village chicken chighirtma', titleRu: 'Чыгыртма из деревенской курицы', price: 22 },
      { title: 'Tabaka, kartof ilə', titleEn: 'Tabaka chicken with potatoes', titleRu: 'Табака с картофелем', price: 22 },
      { title: 'Kiyev kotleti, kartof püresi ilə', titleEn: 'Chicken Kiev with mashed potatoes', titleRu: 'Котлета по-киевски с пюре', price: 16 },
      { title: 'Toyuq kotleti', titleEn: 'Chicken cutlet', titleRu: 'Куриная котлета', price: 10 },
    ],
  },
  {
    slug: 'et-ve-kotletler',
    name: 'Ət və kotletlər',
    nameEn: 'Meat & Cutlets',
    nameRu: 'Мясо и котлеты',
    items: [
      { title: 'Yarpaq dolması', titleEn: 'Yarpaq dolma', titleRu: 'Долма в виноградных листьях', price: 12 },
      { title: 'Ət kotleti, tərəvəz ilə', titleEn: 'Meat cutlet with vegetables', titleRu: 'Мясная котлета с овощами', price: 16 },
      { title: 'Balıq kotleti, kartof püresi ilə', titleEn: 'Fish cutlet with mashed potatoes', titleRu: 'Рыбная котлета с пюре', price: 16 },
    ],
  },
  {
    slug: 'baliq-ve-deniz-mehsullari',
    name: 'Balıq və dəniz məhsulları',
    nameEn: 'Fish & Seafood',
    nameRu: 'Рыба и морепродукты',
    items: [
      { title: 'Salmon, qara düyü ilə', titleEn: 'Salmon with black rice', titleRu: 'Сёмга с чёрным рисом', price: 24 },
      { title: 'Qızıl balıq steyki', titleEn: 'Salmon steak', titleRu: 'Стейк из сёмги', price: 28 },
      { title: 'Forel, tavada', titleEn: 'Pan-fried trout', titleRu: 'Форель на сковороде', price: 24 },
      { title: 'Dorado, tavada', titleEn: 'Pan-fried dorado', titleRu: 'Дорадо на сковороде', price: 26 },
      { title: 'Krevetka Tempura', titleEn: 'Tempura shrimp', titleRu: 'Креветки Темпура', price: 18 },
      { title: 'Krevetka Sarımsaqlı', titleEn: 'Garlic shrimp', titleRu: 'Креветки с чесноком', price: 19 },
      { title: 'Krevetka Dəniz', titleEn: 'Shrimp Sea', titleRu: 'Креветки Море', price: 13 },
      { title: 'Krevetka Okean', titleEn: 'Shrimp Ocean', titleRu: 'Креветки Океан', price: 18 },
      { title: 'Krevetka Dinamik', titleEn: 'Shrimp Dynamic', titleRu: 'Креветки Динамик', price: 20 },
      { title: 'Kalmar halqaları', titleEn: 'Calamari rings', titleRu: 'Кольца кальмара', price: 10 },
    ],
  },
  {
    slug: 'qarnirler',
    name: 'Qarnirlər',
    nameEn: 'Sides',
    nameRu: 'Гарниры',
    items: [
      { title: 'Ev sayağı kartof', titleEn: 'Home-style potatoes', titleRu: 'Картофель по-домашнему', price: 5 },
      { title: 'Kartof püresi', titleEn: 'Mashed potatoes', titleRu: 'Картофельное пюре', price: 5 },
      { title: 'Sadə düyü', titleEn: 'Plain rice', titleRu: 'Простой рис', price: 5 },
      { title: 'Tərəvəzli düyü', titleEn: 'Rice with vegetables', titleRu: 'Рис с овощами', price: 5 },
      { title: 'Qarabaşaq', titleEn: 'Buckwheat', titleRu: 'Гречка', price: 5 },
      { title: 'Qril tərəvəzləri', titleEn: 'Grilled vegetables', titleRu: 'Овощи гриль', price: 5 },
    ],
  },
  {
    slug: 'sovet-klassikasi',
    name: 'Sovet klassikası',
    nameEn: 'Soviet Classics',
    nameRu: 'Советская классика',
    items: [
      { title: 'Siyənək, kartof ilə', titleEn: 'Herring with potatoes', titleRu: 'Селёдка с картофелем', price: 12 },
      {
        title: 'Rus seti, 2 nəfərlik',
        titleRu: 'Русский сет, на 2 персон',
        titleEn: 'Russian Set, for 2',
        price: 30,
        isSet: true,
      },
      {
        title: 'Rus seti, 4 nəfərlik',
        titleRu: 'Русский сет, на 4 персон',
        titleEn: 'Russian Set, for 4',
        price: 50,
        isSet: true,
      },
      { title: 'Ədviyyatlı salo', titleEn: 'Spiced salo', titleRu: 'Пряное сало', price: 10 },
      { title: 'Pelmeni, pendirli', titleEn: 'Pelmeni with cheese', titleRu: 'Пельмени с сыром', price: 14 },
      { title: 'Pelmeni, bulyonlu', titleEn: 'Pelmeni in broth', titleRu: 'Пельмени в бульоне', price: 12 },
      { title: 'Blinçik, göbələkli', titleEn: 'Blini with mushrooms', titleRu: 'Блины с грибами', price: 7 },
      { title: 'Blinçik, toyuqlu', titleEn: 'Blini with chicken', titleRu: 'Блины с курицей', price: 8 },
      { title: 'Blinçik, ətli', titleEn: 'Blini with meat', titleRu: 'Блины с мясом', price: 9 },
    ],
  },
  {
    slug: 'sosis-cesidleri',
    name: 'Sosis çeşidləri',
    nameEn: 'Sausages',
    nameRu: 'Сосиски',
    items: [
      { title: 'İveriya', titleEn: 'Iveria', titleRu: 'Иверия', price: 12 },
      { title: 'Südlü', titleEn: 'Milk sausage', titleRu: 'Молочные', price: 9 },
      { title: 'Ovçu', titleEn: 'Hunter’s sausage', titleRu: 'Охотничьи', price: 9 },
      { title: 'Sardelka', titleEn: 'Sardelka', titleRu: 'Сарделька', price: 14 },
    ],
  },
  {
    slug: 'pive-mezeleri',
    name: 'Pivə məzələri',
    nameEn: 'Beer Snacks',
    nameRu: 'Закуски к пиву',
    items: [
      { title: 'Toyuq çipsi', titleEn: 'Chicken chips', titleRu: 'Куриные чипсы', price: 7 },
      { title: 'Toyuq popkornu', titleEn: 'Chicken popcorn', titleRu: 'Куриный попкорн', price: 8 },
      { title: 'Göbələk çipsi', titleEn: 'Mushroom chips', titleRu: 'Грибные чипсы', price: 5 },
      { title: 'Kolbasa çipsi', titleEn: 'Sausage chips', titleRu: 'Колбасные чипсы', price: 8 },
      { title: 'Krakov topları, pendirli', titleEn: 'Krakow balls with cheese', titleRu: 'Краковские шарики с сыром', price: 15 },
      { title: 'Krakov topları, tomat sousunda', titleEn: 'Krakow balls in tomato sauce', titleRu: 'Краковские шарики в томатном соусе', price: 13 },
      { title: 'Pendirli qrenki', titleEn: 'Cheese croutons', titleRu: 'Гренки с сыром', price: 6 },
      { title: 'Saçaqlı pendir, sadə', titleEn: 'Stringy cheese, plain', titleRu: 'Волокнистый сыр, простой', price: 5 },
      { title: 'Saçaqlı pendir, qızardılmış', titleEn: 'Stringy cheese, fried', titleRu: 'Волокнистый сыр, жареный', price: 6 },
      { title: 'Boğaz, qızardılmış', titleEn: 'Fried pork neck', titleRu: 'Жареное горло', price: 6 },
      { title: 'Boğaz, hisə verilmiş', titleEn: 'Smoked pork neck', titleRu: 'Копчёное горло', price: 8 },
      { title: 'Dorado, hisə verilmiş', titleEn: 'Smoked dorado', titleRu: 'Копчёный дорадо', price: 20 },
      { title: 'Forel, hisə verilmiş', titleEn: 'Smoked trout', titleRu: 'Копчёная форель', price: 18 },
      {
        title: 'Mini çorat qutabı',
        titleEn: 'Mini chorat qutab',
        titleRu: 'Мини-кутаб чорат',
        subtitle: '3 ədəd',
        subtitleEn: '3 pieces',
        subtitleRu: '3 шт.',
        price: 5,
      },
      { title: 'Ət basdırması', titleEn: 'Meat basdyrma', titleRu: 'Мясная басдырма', price: 8 },
      { title: 'Düşbərə', titleEn: 'Dushbara', titleRu: 'Дюшбара', price: 7 },
      { title: 'Gürzə', titleEn: 'Gurza', titleRu: 'Гюрза', price: 8 },
      { title: 'Püstə', titleEn: 'Pistachio', titleRu: 'Фисташки', price: 8 },
      { title: 'Potənək, sadə', titleEn: 'Potenek, plain', titleRu: 'Потенек, простой', price: 6 },
      { title: 'Potənək, zoğal turşulu', titleEn: 'Potenek with cornelian cherry', titleRu: 'Потенек с кизилом', price: 7 },
      { title: 'Noxud', titleEn: 'Roasted chickpeas', titleRu: 'Жареный нохуд', price: 4 },
    ],
  },
  {
    slug: 'buterbrodlar',
    name: 'Buterbrodlar',
    nameEn: 'Sandwiches',
    nameRu: 'Бутерброды',
    items: [
      { title: 'Sprot ilə', titleEn: 'With sprats', titleRu: 'Со шпротами', price: 8 },
      { title: 'Tuna ilə', titleEn: 'With tuna', titleRu: 'С тунцом', price: 13 },
      { title: 'Krevet ilə', titleEn: 'With shrimp', titleRu: 'С креветками', price: 16 },
      { title: 'Hisə verilmiş nərə balığı ilə', titleEn: 'With smoked sturgeon', titleRu: 'С копчёным осетром', price: 18 },
      { title: 'Hisə verilmiş qızıl balıq ilə', titleEn: 'With smoked salmon', titleRu: 'С копчёной сёмгой', price: 17 },
    ],
  },
  {
    slug: 'suzmeli-pive',
    name: 'Süzməli pivə',
    nameEn: 'Draught Beer',
    nameRu: 'Разливное пиво',
    items: [
      {
        title: 'Xırdalan N/F',
        titleEn: 'Khirdalan N/A',
        titleRu: 'Хырдалан б/а',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 3.5,
        priceLabel: '3.50 / 4.00 ₼',
      },
      {
        title: 'Xırdalan',
        titleEn: 'Khirdalan',
        titleRu: 'Хырдалан',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 3.5,
        priceLabel: '3.50 / 4.00 ₼',
      },
      {
        title: 'Brevl N/F',
        titleEn: 'Brevl N/A',
        titleRu: 'Бревл б/а',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 3.5,
        priceLabel: '3.50 / 6.00 ₼',
      },
      {
        title: 'Brevl',
        titleEn: 'Brevl',
        titleRu: 'Бревл',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 3.5,
        priceLabel: '3.50 / 6.00 ₼',
      },
      {
        title: 'Blanc 1664',
        titleEn: 'Blanc 1664',
        titleRu: 'Бланк 1664',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 7.5,
        priceLabel: '7.50 / 8.50 ₼',
      },
      {
        title: 'Alivaria N/F',
        titleEn: 'Alivaria N/A',
        titleRu: 'Аливария б/а',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 5.5,
        priceLabel: '5.50 / 6.50 ₼',
      },
      {
        title: 'Erdinger',
        titleEn: 'Erdinger',
        titleRu: 'Эрдингер',
        subtitle: '0.3 / 0.5 L',
        subtitleEn: '0.3 / 0.5 L',
        subtitleRu: '0.3 / 0.5 л',
        price: 7.5,
        priceLabel: '7.50 / 8.50 ₼',
      },
    ],
  },
  {
    slug: 'susse-pive',
    name: 'Şüşə pivə',
    nameEn: 'Bottled Beer',
    nameRu: 'Бутылочное пиво',
    items: [
      { title: 'Efes Zero', titleEn: 'Efes Zero', titleRu: 'Эфес Зеро', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 6 },
      { title: 'Heineken', titleEn: 'Heineken', titleRu: 'Хайнекен', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 7 },
      { title: 'Corona', titleEn: 'Corona', titleRu: 'Корона', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 8 },
      { title: 'Erdinger', titleEn: 'Erdinger', titleRu: 'Эрдингер', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 9 },
    ],
  },
  {
    slug: 'vodka',
    name: 'Vodka',
    nameEn: 'Vodka',
    nameRu: 'Водка',
    items: [
      { title: 'Absolut', titleEn: 'Absolut', titleRu: 'Абсолют', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 7, priceLabel: '7 / 55 / 90 ₼' },
      { title: 'Finlandia', titleEn: 'Finlandia', titleRu: 'Финляндия', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 7, priceLabel: '7 / 55 / 90 ₼' },
      { title: 'Russkiy Standart', titleEn: 'Russian Standard', titleRu: 'Русский Стандарт', subtitle: '50 ml / 0.7 L / 1 L', subtitleEn: '50 ml / 0.7 L / 1 L', subtitleRu: '50 мл / 0.7 л / 1 л', price: 6, priceLabel: '6 / 60 / 85 ₼' },
      { title: 'Grey Goose', titleEn: 'Grey Goose', titleRu: 'Грей Гуз', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 10, priceLabel: '10 / 160 ₼' },
      { title: 'Louvre', titleEn: 'Louvre', titleRu: 'Лувр', subtitle: '0.5 / 0.7 / 1 L', subtitleEn: '0.5 / 0.7 / 1 L', subtitleRu: '0.5 / 0.7 / 1 л', price: 40, priceLabel: '40 / 54 / 63 ₼' },
      { title: 'Bolşoy Qorod', titleEn: 'Bolshoy Gorod', titleRu: 'Большой Город', subtitle: '0.5 / 0.7 / 1 L', subtitleEn: '0.5 / 0.7 / 1 L', subtitleRu: '0.5 / 0.7 / 1 л', price: 36, priceLabel: '36 / 45 / 54 ₼' },
    ],
  },
  {
    slug: 'nastoyka',
    name: 'Nastoyka',
    nameEn: 'Nastoyka',
    nameRu: 'Настойки',
    items: [
      { title: 'Feyxoa', titleEn: 'Feijoa', titleRu: 'Фейхоа', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 5, priceLabel: '5 / 60 ₼' },
      { title: 'Şaftalı', titleEn: 'Peach', titleRu: 'Персик', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 5, priceLabel: '5 / 60 ₼' },
      { title: 'Albalı', titleEn: 'Sour cherry', titleRu: 'Вишня', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 5, priceLabel: '5 / 60 ₼' },
      { title: 'Qarağilə', titleEn: 'Bilberry', titleRu: 'Черника', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 5, priceLabel: '5 / 60 ₼' },
      { title: 'Moruq', titleEn: 'Raspberry', titleRu: 'Малина', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 5, priceLabel: '5 / 60 ₼' },
      {
        title: 'Nastoyka seti',
        subtitle: '6 ədəd',
        subtitleEn: '6 pieces',
        subtitleRu: '6 штук',
        titleEn: 'Nastoyka Set',
        titleRu: 'Сет настоек',
        price: 28,
        isSet: true,
      },
    ],
  },
  {
    slug: 'serab-ve-sampan',
    name: 'Şərab & Şampan',
    nameEn: 'Wine & Champagne',
    nameRu: 'Вино и Шампанское',
    items: [
      { title: 'Savalan Aleatico, qırmızı', titleEn: 'Savalan Aleatico, red', titleRu: 'Савалан Алеатико, красное', price: 10, priceLabel: '10 / 40 ₼' },
      { title: 'Savalan Moscato, ağ', titleEn: 'Savalan Moscato, white', titleRu: 'Савалан Москато, белое', price: 10, priceLabel: '10 / 40 ₼' },
      { title: 'Savalan Rosé, çəhrayı', titleEn: 'Savalan Rosé', titleRu: 'Савалан Розе', price: 10, priceLabel: '10 / 40 ₼' },
      { title: 'Meysari Marcan, qırmızı', titleEn: 'Meysari Marjan, red', titleRu: 'Мейсари Марджан, красное', price: 42 },
      { title: 'Meysari Sanam, çəhrayı', titleEn: 'Meysari Sanam, rosé', titleRu: 'Мейсари Санам, розе', price: 42 },
      { title: 'Prosecco', titleEn: 'Prosecco', titleRu: 'Просекко', price: 15, priceLabel: '15 / 70 ₼' },
      { title: 'Moët & Chandon', titleEn: 'Moët & Chandon', titleRu: 'Моэт и Шандон', price: 200 },
    ],
  },
  {
    slug: 'viski',
    name: 'Viski',
    nameEn: 'Whisky',
    nameRu: 'Виски',
    items: [
      { title: 'Jameson', titleEn: 'Jameson', titleRu: 'Джемесон', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 9, priceLabel: '9 / 70 / 130 ₼' },
      { title: 'Jack Daniel’s', titleEn: 'Jack Daniel’s', titleRu: 'Джек Дэниелс', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 10, priceLabel: '10 / 80 / 140 ₼' },
      { title: 'Chivas Regal 12', titleEn: 'Chivas Regal 12', titleRu: 'Чивас Ригал 12', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 11, priceLabel: '11 / 95 / 150 ₼' },
      { title: 'Chivas Regal 18', titleEn: 'Chivas Regal 18', titleRu: 'Чивас Ригал 18', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 17, priceLabel: '17 / 250 ₼' },
      { title: 'Monkey Shoulder', titleEn: 'Monkey Shoulder', titleRu: 'Манки Шолдер', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 10, priceLabel: '10 / 200 ₼' },
      { title: 'Glenfiddich 12', titleEn: 'Glenfiddich 12', titleRu: 'Гленфиддик 12', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 12, priceLabel: '12 / 180 ₼' },
      { title: 'Macallan 12', titleEn: 'Macallan 12', titleRu: 'Макаллан 12', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 20, priceLabel: '20 / 300 ₼' },
      { title: 'Glenmorangie', titleEn: 'Glenmorangie', titleRu: 'Гленморанджи', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 20, priceLabel: '20 / 290 ₼' },
    ],
  },
  {
    slug: 'import-spirtli',
    name: 'İmport spirtli',
    nameEn: 'Imported Spirits',
    nameRu: 'Импортный алкоголь',
    items: [
      { title: 'Olmeca Silver / Gold', titleEn: 'Olmeca Silver / Gold', titleRu: 'Ольмека Сильвер / Голд', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 9, priceLabel: '9 / 70 / 130 ₼' },
      { title: 'Patrón Silver', titleEn: 'Patrón Silver', titleRu: 'Патрон Сильвер', subtitle: '50 ml / 0.7 L / 1 L', subtitleEn: '50 ml / 0.7 L / 1 L', subtitleRu: '50 мл / 0.7 л / 1 л', price: 12, priceLabel: '12 / 170 / 200 ₼' },
      { title: 'Hennessy X.O.', titleEn: 'Hennessy X.O.', titleRu: 'Хеннесси X.O.', subtitle: '50 ml', subtitleEn: '50 ml', subtitleRu: '50 мл', price: 18 },
      { title: 'Hennessy V.S.O.P.', titleEn: 'Hennessy V.S.O.P.', titleRu: 'Хеннесси V.S.O.P.', subtitle: '50 ml', subtitleEn: '50 ml', subtitleRu: '50 мл', price: 11 },
      { title: 'Don Julio Silver', titleEn: 'Don Julio Silver', titleRu: 'Дон Хулио Сильвер', subtitle: '50 ml / 0.7 L', subtitleEn: '50 ml / 0.7 L', subtitleRu: '50 мл / 0.7 л', price: 15, priceLabel: '15 / 190 ₼' },
      { title: 'Gordon’s', titleEn: 'Gordon’s', titleRu: 'Гордонс', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 7, priceLabel: '7 / 100 ₼' },
      { title: 'Hendrick’s', titleEn: 'Hendrick’s', titleRu: 'Хендрикс', subtitle: '50 ml / 1 L', subtitleEn: '50 ml / 1 L', subtitleRu: '50 мл / 1 л', price: 10, priceLabel: '10 / 160 ₼' },
      { title: 'Jägermeister', titleEn: 'Jägermeister', titleRu: 'Егермейстер', subtitle: '50 ml / 0.5 L / 1 L', subtitleEn: '50 ml / 0.5 L / 1 L', subtitleRu: '50 мл / 0.5 л / 1 л', price: 9, priceLabel: '9 / 70 / 130 ₼' },
      { title: 'Campari', titleEn: 'Campari', titleRu: 'Кампари', subtitle: '50 ml', subtitleEn: '50 ml', subtitleRu: '50 мл', price: 7 },
      { title: 'Martini Rosso', titleEn: 'Martini Rosso', titleRu: 'Мартини Россо', subtitle: '50 ml', subtitleEn: '50 ml', subtitleRu: '50 мл', price: 9 },
    ],
  },
  {
    slug: 'limonad-ve-soyuq-ickiler',
    name: 'Limonad & soyuq içkilər',
    nameEn: 'Lemonades & Cold Drinks',
    nameRu: 'Лимонады и холодные напитки',
    items: [
      {
        title: 'Limonad',
        titleEn: 'Lemonade',
        titleRu: 'Лимонад',
        subtitle: 'Tərxun, Düşes, Portağal — 0.33 L / 1 L',
        subtitleEn: 'Tarragon, Duchess, Orange — 0.33 L / 1 L',
        subtitleRu: 'Тархун, Дюшес, Апельсин — 0.33 л / 1 л',
        price: 8,
        priceLabel: '8 / 16 ₼',
      },
      {
        title: 'Soyuq çay',
        titleEn: 'Iced tea',
        titleRu: 'Холодный чай',
        subtitle: 'Limon, Şaftalı, Qarpız — 0.33 L / 1 L',
        subtitleEn: 'Lemon, Peach, Watermelon — 0.33 L / 1 L',
        subtitleRu: 'Лимон, Персик, Арбуз — 0.33 л / 1 л',
        price: 6,
        priceLabel: '6 / 12 ₼',
      },
      {
        title: 'Təbii sıxma şirə',
        titleEn: 'Fresh-squeezed juice',
        titleRu: 'Свежевыжатый сок',
        subtitle: 'Nar / Portağal / Alma',
        subtitleEn: 'Pomegranate / Orange / Apple',
        subtitleRu: 'Гранат / Апельсин / Яблоко',
        price: 6,
        priceLabel: '6 / 8 / 6 ₼',
      },
      { title: 'Turşməzə bir şey', titleEn: 'Something sweet-and-sour', titleRu: 'Что-то кисло-сладкое', price: 8 },
    ],
  },
  {
    slug: 'sular-ve-alkoqolsuz',
    name: 'Sular & alkoqolsuz içkilər',
    nameEn: 'Waters & Soft Drinks',
    nameRu: 'Вода и безалкогольные',
    items: [
      { title: 'Sirab qazlı / qazsız', titleEn: 'Sirab sparkling / still', titleRu: 'Сираб газированная / негаз.', subtitle: '0.33 / 0.75 L', subtitleEn: '0.33 / 0.75 L', subtitleRu: '0.33 / 0.75 л', price: 5, priceLabel: '5 / 7 ₼' },
      { title: 'Coca-Cola / Fanta / Sprite', titleEn: 'Coca-Cola / Fanta / Sprite', titleRu: 'Кока-Кола / Фанта / Спрайт', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 5 },
      { title: 'Kompot', titleEn: 'Kompot', titleRu: 'Компот', subtitle: '0.25 / 1 L', subtitleEn: '0.25 / 1 L', subtitleRu: '0.25 / 1 л', price: 4, priceLabel: '4 / 10 ₼' },
      { title: 'Fuse Tea', titleEn: 'Fuse Tea', titleRu: 'Фьюз Ти', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 5 },
      { title: 'Sarıkız', titleEn: 'Sarıkız', titleRu: 'Сарыкыз', subtitle: '0.2 L', subtitleEn: '0.2 L', subtitleRu: '0.2 л', price: 4 },
      { title: 'Red Bull', titleEn: 'Red Bull', titleRu: 'Ред Булл', subtitle: '0.225 L', subtitleEn: '0.225 L', subtitleRu: '0.225 л', price: 8 },
      { title: 'Təbii şirə', titleEn: 'Natural juice', titleRu: 'Натуральный сок', subtitle: '0.25 / 1 L', subtitleEn: '0.25 / 1 L', subtitleRu: '0.25 / 1 л', price: 4, priceLabel: '4 / 10 ₼' },
      { title: 'Borjomi', titleEn: 'Borjomi', titleRu: 'Боржоми', subtitle: '0.5 L', subtitleEn: '0.5 L', subtitleRu: '0.5 л', price: 5 },
      { title: 'Tonik', titleEn: 'Tonic', titleRu: 'Тоник', subtitle: '0.33 L', subtitleEn: '0.33 L', subtitleRu: '0.33 л', price: 5 },
    ],
  },
  {
    slug: 'isti-ickiler',
    name: 'İsti içkilər',
    nameEn: 'Hot Drinks',
    nameRu: 'Горячие напитки',
    items: [
      { title: 'Çay, qara / yaşıl', titleEn: 'Tea, black / green', titleRu: 'Чай, чёрный / зелёный', price: 10 },
      { title: 'İsti şokolad', titleEn: 'Hot chocolate', titleRu: 'Горячий шоколад', price: 5 },
      { title: 'Kakao', titleEn: 'Cocoa', titleRu: 'Какао', price: 5 },
    ],
  },
  {
    slug: 'cay-destgahi',
    name: 'Çay dəstgahı',
    nameEn: 'Tea Ceremonies',
    nameRu: 'Чайная церемония',
    items: [
      {
        title: 'Çay dəstgahı',
        titleEn: 'Tea Ceremony',
        titleRu: 'Чайная церемония',
        description: 'Çay, quru meyvə, çərəz, mürəbbə, Napoleon, paxlava',
        descriptionEn: 'Tea, dried fruits, nuts, jam, Napoleon, baklava',
        descriptionRu: 'Чай, сухофрукты, орехи, варенье, Наполеон, пахлава',
        price: 50,
        isSet: true,
      },
      {
        title: 'Çay dəstgahı + qəlyan',
        titleEn: 'Tea Ceremony + Hookah',
        titleRu: 'Чайная церемония + кальян',
        description: 'Çay, mürəbbə, 2 ədəd paxlava, çərəz, quru meyvə, qəlyan',
        descriptionEn: 'Tea, jam, 2 pieces of baklava, nuts, dried fruits, hookah',
        descriptionRu: 'Чай, варенье, 2 шт. пахлавы, орехи, сухофрукты, кальян',
        price: 75,
        isSet: true,
      },
    ],
  },
  {
    slug: 'sirniyyat',
    name: 'Şirniyyat',
    nameEn: 'Desserts',
    nameRu: 'Десерты',
    items: [
      { title: 'Ballı tort', titleEn: 'Honey cake', titleRu: 'Медовик', price: 7 },
      { title: 'Napoleon', titleEn: 'Napoleon', titleRu: 'Наполеон', price: 5 },
      { title: 'Mürəbbə', titleEn: 'Jam', titleRu: 'Варенье', price: 7 },
      { title: 'Halva', titleEn: 'Halva', titleRu: 'Халва', price: 5 },
      { title: 'Çərəz', titleEn: 'Nuts', titleRu: 'Орехи', price: 12 },
      { title: 'Quru meyvə', titleEn: 'Dried fruits', titleRu: 'Сухофрукты', price: 12 },
      { title: 'Meyvə tabağı', titleEn: 'Fruit platter', titleRu: 'Фруктовая тарелка', price: 18 },
      { title: 'Dondurma', titleEn: 'Ice cream', titleRu: 'Мороженое', price: 7 },
      {
        title: 'Paxlava',
        titleEn: 'Baklava',
        titleRu: 'Пахлава',
        subtitle: 'milli / türk / südlü',
        subtitleEn: 'national / Turkish / milk',
        subtitleRu: 'национальная / турецкая / молочная',
        price: 7,
      },
    ],
  },
  {
    slug: 'qelyan',
    name: 'Qəlyan',
    nameEn: 'Hookah',
    nameRu: 'Кальян',
    items: [
      { title: 'Premium', titleEn: 'Premium', titleRu: 'Премиум', price: 45 },
      { title: 'Sadə', titleEn: 'Standard', titleRu: 'Обычный', price: 35 },
    ],
  },
  {
    slug: 'eylence-menyusu',
    name: 'Pabeda əyləncə menyusu 😄',
    nameEn: 'Pabeda Fun Menu 😄',
    nameRu: 'Развлекательное меню Победы 😄',
    items: [
      {
        title: 'Qarsonu qov getsin',
        titleEn: 'Fire the waiter',
        titleRu: 'Уволить официанта',
        description: '"Gör nə edirsən..." işdən azad etmək.',
        descriptionEn: '"Look what you’ve done..." — dismissal on the spot.',
        descriptionRu: '«Смотри, что натворил...» — увольнение на месте.',
        price: 1000,
      },
      {
        title: 'Aşbazı spisat eləmək',
        titleEn: 'Write off the cook',
        titleRu: 'Списать повара',
        description: '"Gör nə edirsən..." işdən azad etmək.',
        descriptionEn: '"Look what you’ve done..." — dismissal on the spot.',
        descriptionRu: '«Смотри, что натворил...» — увольнение на месте.',
        price: 3000,
      },
      {
        title: 'Meneceri qaraltmaq',
        titleEn: 'Blacken the manager',
        titleRu: 'Загасить менеджера',
        description: '"Gör nə edirsən..." işdən azad etmək.',
        descriptionEn: '"Look what you’ve done..." — dismissal on the spot.',
        descriptionRu: '«Смотри, что натворил...» — увольнение на месте.',
        price: 5000,
      },
    ],
  },
]

// Default settings seeded on first run. All are editable from the admin
// settings page. Colors are stored here so they can be changed without a redeploy.
export const defaultSettings: Record<string, string> = {
  shop_name: 'PABEDA',
  shop_name_en: 'PABEDA',
  shop_name_ru: 'PABEDA',

  tagline: 'Nostalji atmosfer, klassik dadlar',
  tagline_en: 'Nostalgic atmosphere, classic tastes',
  tagline_ru: 'Ностальгическая атмосфера, классические вкусы',

  about:
    'Pabeda — Bakının qəlbində, hər süfrədən ev istiliyi gələn bir yerdir. Ənənəvi Azərbaycan və Sovet mətbəxinin ən yaxşı yeməklərini müasir təqdimatla birlikdə təklif edirik.',
  about_en:
    'Pabeda sits in the heart of Baku, where every table carries the warmth of home. We serve the best of traditional Azerbaijani and Soviet cuisine with a modern touch.',
  about_ru:
    'Pabeda — в сердце Баку, где за каждым столом чувствуется тепло дома. Лучшее из традиционной азербайджанской и советской кухни в современной подаче.',

  hours: 'Hər gün 15:00 – 02:00',
  hours_en: 'Every day 15:00 – 02:00',
  hours_ru: 'Ежедневно 15:00 – 02:00',

  address: 'Bəsti Bağırova küç. 2A, Bakı',
  address_en: 'Basti Bagirova st. 2A, Baku',
  address_ru: 'ул. Бести Багировой 2А, Баку',

  phone: '+994 50 702 72 22',
  email: '',
  whatsapp: 'https://wa.me/994507027222',
  instagram: 'https://www.instagram.com/pabeda.restoran/',
  facebook: '',

  service_charge_note: '10% xidmət haqqı hesabınıza əlavə olunur.',
  service_charge_note_en: 'A 10% service charge is added to your bill.',
  service_charge_note_ru: 'К счёту добавляется 10% за обслуживание.',

  currency_symbol: '₼',
  default_locale: 'az',

  theme_primary: '#D91E1E',
  theme_accent: '#C89632',
}
